# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: requestphishing.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'requestphishing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15requestphishing.proto\x12\x07service\"\"\n\x0fPhishingRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"K\n\x13\x43omputationResponse\x12\x13\n\x0bis_phishing\x18\x01 \x01(\x08\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x03(\t2g\n\x10PhishingDetector\x12S\n\x17RequestCheckingPhishing\x12\x18.service.PhishingRequest\x1a\x1c.service.ComputationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requestphishing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PHISHINGREQUEST']._serialized_start=34
  _globals['_PHISHINGREQUEST']._serialized_end=68
  _globals['_COMPUTATIONRESPONSE']._serialized_start=70
  _globals['_COMPUTATIONRESPONSE']._serialized_end=145
  _globals['_PHISHINGDETECTOR']._serialized_start=147
  _globals['_PHISHINGDETECTOR']._serialized_end=250
# @@protoc_insertion_point(module_scope)
